from fpdf import FPDF
from datetime import datetime
import pandas as pd
import json
import os
import tempfile
import plotly.io as pio


class MarketingReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.brand_color = (108, 99, 255)   # Purple
        self.success_color = (0, 200, 150)
        self.danger_color = (255, 75, 110)
        self.text_dark = (15, 23, 42)
        self.text_muted = (100, 116, 139)
        self.bg_light = (248, 250, 252)

    def header(self):
        self.set_fill_color(*self.brand_color)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(255, 255, 255)
        self.set_y(5)
        self.cell(0, 8, "AI MARKETING CAMPAIGN ANALYZER  |  DIGIDARTS", align="C")
        self.ln(18)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*self.text_muted)
        self.cell(0, 6,
                  f"Generated by AI Marketing Analyzer  |  {datetime.now().strftime('%d %b %Y %H:%M')}  |  Page {self.page_no()}",
                  align="C")

    def section_title(self, title: str):
        self.ln(6)
        self.set_fill_color(*self.brand_color)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 9, f"  {title.upper()}", fill=True, ln=True)
        self.ln(3)

    def metric_box(self, label: str, value: str, color: tuple = None):
        color = color or self.brand_color
        x, y = self.get_x(), self.get_y()
        w, h = 42, 22
        self.set_fill_color(*self.bg_light)
        self.rect(x, y, w, h, "F")
        self.set_fill_color(*color)
        self.rect(x, y, 3, h, "F")
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*self.text_muted)
        self.set_xy(x + 5, y + 3)
        self.cell(w - 7, 5, label.upper())
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.text_dark)
        self.set_xy(x + 5, y + 10)
        self.cell(w - 7, 8, str(value))

    def body_text(self, text: str, indent: int = 0):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.text_dark)
        self.set_x(10 + indent)
        self.multi_cell(190 - indent, 5.5, str(text))

    def bullet_item(self, text: str, color: tuple = None):
        color = color or self.brand_color
        self.set_fill_color(*color)
        self.set_x(12)
        self.rect(12, self.get_y() + 2.5, 2, 2, "F")
        self.set_x(17)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.text_dark)
        self.multi_cell(183, 5.5, str(text))


def generate_report(
    df: pd.DataFrame,
    summary: dict,
    analysis: dict,
    output_path: str = None,
) -> bytes:
    """
    Generate full PDF report. Returns bytes for Streamlit download.
    """
    pdf = MarketingReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Title block ──
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(15, 23, 42)
    pdf.ln(2)
    pdf.cell(0, 10, "Campaign Performance Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 7, datetime.now().strftime("Generated on %A, %d %B %Y"), ln=True, align="C")
    pdf.ln(6)

    # ── KPI Cards ──
    pdf.section_title("Portfolio KPIs")
    metrics = [
        ("Total Spend", f"${summary['total_spend']:,.0f}"),
        ("Total Revenue", f"${summary['total_revenue']:,.0f}"),
        ("Portfolio ROAS", f"{summary['portfolio_roas']:.2f}x"),
        ("Total Conversions", f"{summary['total_conversions']:,}"),
    ]
    gap = 4
    card_w = 42
    start_x = (210 - (len(metrics) * card_w + (len(metrics) - 1) * gap)) / 2
    y = pdf.get_y()
    for i, (label, val) in enumerate(metrics):
        pdf.set_xy(start_x + i * (card_w + gap), y)
        colors = [pdf.brand_color, pdf.success_color, (55, 190, 248), (167, 139, 250)]
        pdf.metric_box(label, val, colors[i])
    pdf.ln(30)

    metrics2 = [
        ("Active Campaigns", str(summary["active_campaigns"])),
        ("Avg CTR", f"{summary['avg_ctr']:.2f}%"),
        ("Avg CPC", f"${summary['avg_cpc']:.2f}"),
        ("Avg CPA", f"${summary['avg_cpa']:.2f}"),
    ]
    y = pdf.get_y()
    for i, (label, val) in enumerate(metrics2):
        pdf.set_xy(start_x + i * (card_w + gap), y)
        pdf.metric_box(label, val, pdf.text_muted)
    pdf.ln(30)

    # ── Executive Summary ──
    pdf.section_title("Executive Summary")
    pdf.body_text(analysis.get("executive_summary", "No summary available."))

    # ── Top Performers ──
    pdf.section_title("Top Performing Campaigns")
    performers = analysis.get("top_performers", [])
    if isinstance(performers, list):
        for item in performers:
            if isinstance(item, dict):
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(*pdf.text_dark)
                pdf.set_x(12)
                name = item.get("campaign_name", item.get("name", "Campaign"))
                pdf.cell(0, 6, f"✦  {name}", ln=True)
                reason = item.get("reason", item.get("why", ""))
                if reason:
                    pdf.body_text(reason, indent=8)
            else:
                pdf.bullet_item(str(item), pdf.success_color)
    pdf.ln(2)

    # ── Underperformers ──
    pdf.section_title("Underperforming Campaigns")
    underperformers = analysis.get("underperformers", [])
    if isinstance(underperformers, list):
        for item in underperformers:
            if isinstance(item, dict):
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(*pdf.danger_color)
                pdf.set_x(12)
                name = item.get("campaign_name", item.get("name", "Campaign"))
                pdf.cell(0, 6, f"⚠  {name}", ln=True)
                problem = item.get("problem", item.get("issue", ""))
                if problem:
                    pdf.set_text_color(*pdf.text_dark)
                    pdf.body_text(problem, indent=8)
            else:
                pdf.bullet_item(str(item), pdf.danger_color)
    pdf.ln(2)

    # ── Optimization Recommendations ──
    pdf.section_title("AI Optimization Recommendations")
    recs = analysis.get("recommendations", [])
    if isinstance(recs, list):
        for rec in recs:
            if isinstance(rec, dict):
                camp = rec.get("campaign", rec.get("campaign_name", ""))
                action = rec.get("action", rec.get("recommendation", str(rec)))
                if camp:
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.set_text_color(*pdf.brand_color)
                    pdf.set_x(12)
                    pdf.cell(0, 6, camp, ln=True)
                    pdf.body_text(action, indent=8)
                else:
                    pdf.bullet_item(action)
            else:
                pdf.bullet_item(str(rec))
    pdf.ln(2)

    # ── Budget Reallocation ──
    budget_plan = analysis.get("budget_plan", analysis.get("budget_reallocation_plan", ""))
    if budget_plan:
        pdf.section_title("Budget Reallocation Plan")
        if isinstance(budget_plan, dict):
            for k, v in budget_plan.items():
                pdf.bullet_item(f"{k}: {v}")
        elif isinstance(budget_plan, list):
            for item in budget_plan:
                pdf.bullet_item(str(item))
        else:
            pdf.body_text(str(budget_plan))

    # ── Projected Improvement ──
    projection = analysis.get("projected_improvement", "")
    if projection:
        pdf.section_title("Projected Improvement")
        pdf.body_text(str(projection))

    # ── Campaign Data Table ──
    pdf.add_page()
    pdf.section_title("Full Campaign Data")
    cols = ["campaign_name", "platform", "spend", "revenue", "roas", "ctr", "conversions", "status"]
    headers = ["Campaign", "Platform", "Spend", "Revenue", "ROAS", "CTR%", "Conv.", "Status"]
    widths = [52, 28, 22, 22, 18, 14, 16, 18]

    pdf.set_fill_color(*pdf.brand_color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    for h, w in zip(headers, widths):
        pdf.cell(w, 8, h, border=0, fill=True, align="C")
    pdf.ln()

    for i, (_, row) in enumerate(df[cols].iterrows()):
        bg = (248, 250, 252) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*pdf.text_dark)
        pdf.set_font("Helvetica", "", 8)
        vals = [
            str(row["campaign_name"])[:28],
            str(row["platform"]),
            f"${row['spend']:,.0f}",
            f"${row['revenue']:,.0f}",
            f"{row['roas']:.2f}x",
            f"{row['ctr']:.1f}%",
            str(int(row["conversions"])),
            str(row["status"]),
        ]
        for val, w in zip(vals, widths):
            pdf.cell(w, 6.5, val, fill=True, align="C")
        pdf.ln()

    pdf_bytes = bytes(pdf.output())
    if output_path:
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
    return pdf_bytes
